### ISSUE TITLE
Issue by submitting the file 

### ISSUE THREAD

**Issue by Carnbiophysix** [b-pardi/BraTaDio#9]
Hello, 

I am not able to submit the file informations, when i try to do it I obtain this message in the picture...
I tried to figgure what to do but it seems that i am very bad at coding...

Is someone able to help me?

Thank you very much, 

Carn
![Capture d’écran 2024-07-09 à 15 29 37](https://github.com/b-pardi/BraTaDio/assets/175128275/421a31cb-bdf5-434d-acf9-a6943a444b30)

**Comment by b-pardi** [comment]
Hi @Carnbiophysix , can you please send me the file you are trying to work with so I can take a look?
The error seems to be coming from the qsd file formatting routine

**Comment by diego-nasc** [comment]
Hi, 

I’m running into a similar problem.
When I try to submit the file information from the GUI, I get:

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\tkinter\__init__.py", line 1967, in __call__    
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\...\pyQCM-master\main.py", line 1367, in col_names_submit
    format_raw_data(input.file_src_type, input.file, input.will_use_theoretical_vals)
  File "C:\Users\\...\pyQCM-master\src\format_file.py", line 312, in format_raw_data
    data_df = open_df_from_file(data_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\pyQCM-master\src\format_file.py", line 39, in open_df_from_file
    df = extract_sensor_data(*read_qsd(file))
                              ^^^^^^^^^^^^^^
  File "C:\Users\...\pyQCM-master\pyQCM-master\src\format_qsd.py", line 75, in read_qsd
    timtmp = (val - val[0]) * 86400
                   ~~~^^^
IndexError: index 0 is out of bounds for axis 0 with size 0`

Environment: Windows 11, Python 3.10.x (Anaconda/Spyder 5.x).

I can share the [qsd](https://drive.google.com/file/d/1267fFNoDFJNQSRc9Q7StvNobuj3M7i6j/view?usp=drive_link) file that triggers the error if that helps.

 Please let me know what additional details would be useful for diagnosis.

**Comment by b-pardi** [comment]
Hi @diego-nasc, yes if you could please share the qsd file that would be appreciated. Thanks!
